### ISSUE TITLE
QQ登录错误 Code码：46

### ISSUE THREAD

**Issue by maoweijiajia** [kosaka-bun/jar-launcher#6]
在使用 Mirai 协议时，遇到了如下错误：

Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2058709391), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)

尽管已尝试更换 QQ 号和 Mirai 协议版本，问题仍未解决。请问是否有其他解决方案或排查方法？

**Comment by kosaka-bun** [comment]
最近更新的2.0.0版本正是为了处理这一问题。

mirai框架也已经长期没有更新了，目前QQ机器人普遍采用基于QQ NT客户端的方案来实现，即在一个安装了QQ NT的系统中，为QQ NT安装一个插件，或是直接与QQ NT的核心进行通信，来达到自动操作官方QQ客户端的效果。

这些基于QQ NT的框架有：
https://github.com/LLOneBot/LLOneBot
https://github.com/NapNeko/NapCatQQ

它们均对外提供基于onebot标准的http与WebSocket接口。

starter 2.0.0版本已实现对OneBot 11标准的支持，文档暂未更新，但可以先提供一个配置文件示例。

**Comment by kosaka-bun** [comment]
```yaml
honoka:
  qqrobot:
    # 指定一个机器人框架的实现
    framework: onebot
    admin-qq: 123456
    developing-group: 123456
    onebot:
      host: localhost
      # onebot正向websocket端口
      websocket-port: 3001
      # onebot http端口
      http-port: 3101
      # file-receiver的端口，当onebot框架不在本机上时需要
      file-receiver-port: 8081
```
